     apiVersion: v1
     kind: ConfigMap
     metadata:
       name: custom-nginx-config
       namespace: homework
     data:
      default.conf: |
        server {
            listen       80;
            server_name  localhost;

            #charset koi8-r;
            #access_log  /var/log/nginx/host.access.log  main;

            location / {
                root   /homework;
                index  index.html index.htm;
            }
        }
     
