apiVersion: v2
name: otus-app
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: mysql
    version: "11.1.15"
    repository: https://charts.bitnami.com/bitnami