apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: otus-secret-store
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "otus" 
      version: "v2"
      auth:
        kubernetes: 
          mountPath: "otus"
          role: "otus"
          serviceAccountRef:
            name: "vault" 
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otus-secret
  namespace: vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: otus-secret-store 
    kind: SecretStore
  target:
    name: vault-secrets 
  data:
    - secretKey: username
      remoteRef:
        key: cred 
        property: username 
    - secretKey: password
      remoteRef:
        key: cred
        property: password