apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
   app: nginx
spec:
 replicas: 3
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
     labels:
       app: nginx
   spec:
    containers:
    - name: nginx
      image: nginx:1.14.2
      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - test -S /homework/index.html      
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm /homework/index.html"]
      volumeMounts:
      - mountPath: /homework
        name: workdir    
      ports:
      - containerPort: 8000
    initContainers:
    - name: html
      image: busybox:1.28
      command: 
      - wget
      - "-O"
      - "/init/index.html"
      - http://info.cern.ch
      volumeMounts:
      - mountPath: /init
        name: workdir
    volumes:
      - name: workdir
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1