---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus
spec:
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - git@github.com:Kuber-2024-06OTUS/frexin_repo.git
status: {}